sudo: required
services:
  - docker
language: ruby
rvm:
  - 2.3.6

matrix:
    allow_failures:

cache: bundler

before_install:
    - docker build -t 2maz/apaka .
    - docker run --privileged -d 2maz/apaka tail -f /dev/null
    - docker ps -a
    - docker run --privileged 2maz/apaka /bin/sh -c "cd /home/docker/apaka/; bundle exec rake test"

script:
    - bundle exec rake test
