sudo: true
dist: xenial
language: ruby
rvm:
  - 2.3.6

matrix:
    allow_failures:

cache: bundler

before_install:
    - sudo apt-get -qq update
    - sudo apt-get install -y gem2deb reprepro apache2 pbuilder cowbuilder cowdancer
install:
    - git config --global user.name "Apaka on Travis CI"
    - git config --global user.email "apaka@travis"
    - gem install bundler
    - gem install autoproj
    # Some tests expect gems to be present in vendor/bundle
    - bundle install --path vendor/bundle
script:
    - bundle exec rake
    - bundle exec rake test
